mex fcslateral.c      
mex fcsselector.c     
mex fcssgq.c          
mex machno.c          
mex fcslongitudinal.c 
mex fcssgnz.c         
mex fcsu0.c           
mex fcsnz.c           
mex fcssgp.c          
mex fcsx0.c          