#Makefil för Hkginterp

sym:    makefile sym.h sym.c sym.inc lip3.c lip2.c lip1.c
	gcc sym.c -o sym

asym:    makefile asym.h asym.c asym.inc lip3.c lip2.c lip1.c
	gcc asym.c -o asym

conv:	makefile convert.c
	gcc convert.c -o convert